name: Build & Release Null VPN

on:
  workflow_dispatch: # اجازه اجرای دستی با یک کلیک (بدون نیاز به تگ زدن)
  push:
    tags:
      - 'v*'

permissions:
  contents: write # ⚠️ این خط برای آپلود فایل دانلودی اجباری است

jobs:
  build-desktop:
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22 # ارتقا به نسخه ۲۲ برای حذف اخطار

      - name: Install Dependencies
        run: npm install

      - name: Build & Package Electron (.exe)
        run: npm run electron:build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/') || github.event_name == 'workflow_dispatch'
        with:
          files: |
            release/*.exe
            release/*.blockmap
